### ISSUE TITLE
Node IDs should be UUIDS

### ISSUE THREAD

**Issue by siwells** [ARG-ENU/monkeypuzzle_web#19]
Node IDs should be UUIDS that are conformant with those generated by Python and used in SADFace.

**Comment by nathanrmair** [comment]
Hi Simon, I thought they were. The UUID generator was just a StackOverflow find, what should I look for to make it conformant?

**Comment by siwells** [comment]
Yeah, you're right. I'd checked the downloade JSON from the "you're going to die" example which doesn't contain valid UUIDS (because I put it together before the SADFace library was ready as an example of how it should look). JSON generated from new atoms added via the interface are fine.
