### ISSUE TITLE
Unnecessary <a> tag in Index.html

### ISSUE THREAD

**Issue by ske66** [ARG-ENU/monkeypuzzle_web#62]
found an A tag that hadn't been closed. Doesn't seem to have caused any issues but may further down the line. Can be found on line 94.

**Comment by siwells** [comment]
Fixed. Removed the opening tag and no harm appears to be done. Note that most browsers will automatically insert closing tags in sensible places if they can (which is what was happening in this case and which is why there were no adverse effects).
