### ISSUE TITLE
Clean up console.log messages from JS

### ISSUE THREAD

**Issue by siwells** [ARG-ENU/monkeypuzzle_web#9]
A bunch of console.log messages are still displayed and left-over from development process

**Comment by nathanrmair** [comment]
Should this include the 'console.log(ex)' for try/catch in sadface? I just implemented these as found in python. Currently cleaning assuming this is not the case.

**Comment by siwells** [comment]
I think logging errors & exceptions is fine, but any development related stuff, e.g. value of variables, is better not logged as a rule. That would be my current distinction.
